### ISSUE TITLE
Login session name

### ISSUE THREAD

**Issue by megsum** [C3912015/OceanObservationSystem#1]
I am trying to transfer the username from the login page to the subscribe page, but it does not work unless I comment out session_name('Login');

Is it okay if I keep it commented out, or is it used for something else?

**Comment by jchang3** [comment]
session_name('Login') names the cookie. I'm not entirely sure what the behaviour of the session will be if you remove the name. It shouldn't have any affect on other portions of your code. If you need to access the username you just have something like $your_username_variable = $_SESSION['usr]; in your subscribe.php

**Comment by LeahGabrielle** [comment]
I'm having an issue with $_SESSION['role'] being empty when I'm trying to use it. I used session_start(), then tried to print the user role. Is there something I'm missing that I also need?

**Comment by jchang3** [comment]
Are you logged in as a user? Make sure cookies are enabled as well for your
browser and possibly try logging out and deleting the cookie.. All session
globals are assigned once a valid user has been detected in the database.
Once you use session start it should automatically read the cookie if it
hasn't expired for the session id and then get all the other globals.

**Comment by LeahGabrielle** [comment]
Thanks, figured it out.
